// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/ws/configure_client.ts";
import * as $4 from "./routes/api/ws/index.ts";
import * as $5 from "./routes/api/ws/online.ts";
import * as $6 from "./routes/api/ws/register_client.ts";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/Chat.tsx";
import * as $$1 from "./islands/hooks/use-ws/connect.fn.ts";
import * as $$2 from "./islands/hooks/use-ws/disconnect.fn.ts";
import * as $$3 from "./islands/hooks/use-ws/effect.fn.ts";
import * as $$4 from "./islands/hooks/use-ws/hook.ts";
import * as $$5 from "./islands/hooks/use-ws/http_to_ws.fn.ts";
import * as $$6 from "./islands/hooks/use-ws/types.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/ws/configure_client.ts": $3,
    "./routes/api/ws/index.ts": $4,
    "./routes/api/ws/online.ts": $5,
    "./routes/api/ws/register_client.ts": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
    "./islands/hooks/use-ws/connect.fn.ts": $$1,
    "./islands/hooks/use-ws/disconnect.fn.ts": $$2,
    "./islands/hooks/use-ws/effect.fn.ts": $$3,
    "./islands/hooks/use-ws/hook.ts": $$4,
    "./islands/hooks/use-ws/http_to_ws.fn.ts": $$5,
    "./islands/hooks/use-ws/types.ts": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
